version: '3.4'

services:
  doitsu.fandom.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "44300:80"
  doitsu.fandom.adminr2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "44400:80"
  doitsu.fandom.client_homepage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "44500:80"

