version: '3.4'

services:
  doitsu.fandom.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9092:80"
  doitsu.fandom.adminr2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9091:80"
  doitsu.fandom.client_homepage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9090:80"

