fandom_api:
    image: "hub.doitsu.tech:5000/fandom_api:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9092:80"
      
fandom_adminr2:
    image: "hub.doitsu.tech:5000/fandom_adminr2:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9091:80"
      
fandom_homepage:
    image: "hub.doitsu.tech:5000/fandom_homepage:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9090:80"
      